# Generated by Django 3.2.5 on 2022-01-08 14:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('uuid', models.CharField(max_length=50)),
                ('no', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('pno', models.CharField(max_length=4)),
                ('credit', models.PositiveSmallIntegerField()),
                ('create_date', models.DateTimeField(null=True)),
                ('modify_date', models.DateTimeField(null=True)),
                ('is_activate', models.PositiveSmallIntegerField(default=1)),
                ('is_show', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uuid', models.CharField(max_length=50)),
                ('no', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(default='男', max_length=2)),
                ('age', models.PositiveSmallIntegerField()),
                ('department', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField(null=True)),
                ('modify_date', models.DateTimeField(null=True)),
                ('is_show', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('last_login', models.DateTimeField(default=datetime.datetime(2022, 1, 8, 14, 0, 52, 543067))),
                ('create_date', models.DateTimeField(null=True)),
                ('modify_date', models.DateTimeField(null=True)),
                ('user_type', models.PositiveSmallIntegerField(default=0)),
                ('is_activate', models.PositiveSmallIntegerField(default=1)),
                ('is_show', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SC',
            fields=[
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('grade', models.PositiveSmallIntegerField(default=0)),
                ('create_date', models.DateTimeField(null=True)),
                ('modify_date', models.DateTimeField(null=True)),
                ('is_show', models.PositiveSmallIntegerField(default=1)),
                ('course_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.course')),
                ('student_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.student')),
            ],
        ),
    ]
